import type {
  Composition,
  Lighting,
  LocationType,
  Mood,
  PaletteTone,
  ProjectCategory,
  StudioServiceId,
  VisualQuality,
} from "@/types/project";

/**
 * The studio's shared visual vocabulary. Labels and phrases are editorial copy;
 * the lexicon maps everyday words to the structured facets used by discovery.
 */

export const qualityCopy: Readonly<Record<VisualQuality, { label: string; phrase: string }>> = {
  cinematic: { label: "Cinematic", phrase: "frames composed like stills from a film, with atmosphere carrying the story" },
  raw: { label: "Raw", phrase: "unpolished, candid moments where imperfection is part of the truth" },
  intimate: { label: "Intimate", phrase: "a close, unhurried distance that lets small gestures matter" },
  minimal: { label: "Minimal", phrase: "pared-back frames where space and material do the work" },
  dramatic: { label: "Dramatic", phrase: "deep shadow, strong shape, and light used with intent" },
  warm: { label: "Warm", phrase: "sun-warmed tones and a gentle, human temperature" },
  monochrome: { label: "Monochrome", phrase: "black-and-white tonality where form and contrast lead" },
  architectural: { label: "Architectural", phrase: "line, threshold, and proportion treated as subject" },
  editorial: { label: "Editorial", phrase: "considered sequencing with a clear point of view, as if made for print" },
  nostalgic: { label: "Nostalgic", phrase: "a sense of memory, weathered surfaces, and old-world light" },
  experimental: { label: "Experimental", phrase: "unexpected technique, abstraction, and risk-taking in the frame" },
};

export const moodCopy: Readonly<Record<Mood, string>> = {
  quiet: "Quiet",
  tender: "Tender",
  romantic: "Romantic",
  contemplative: "Contemplative",
  sensual: "Sensual",
  convivial: "Convivial",
  timeless: "Timeless",
  serene: "Serene",
};

export const lightingCopy: Readonly<Record<Lighting, { label: string; phrase: string }>> = {
  "golden-hour": { label: "Golden hour", phrase: "low, golden sun that rakes across texture and skin" },
  dusk: { label: "Dusk", phrase: "the last blue-gold minutes of evening, holding detail in the shadows" },
  candlelight: { label: "Candlelight", phrase: "practical candlelight that lets faces glow while the room falls away" },
  "window-light": { label: "Window light", phrase: "soft directional window light, shaped rather than added" },
  "open-shade": { label: "Open shade", phrase: "even open shade for honest colour and gentle skin" },
  dappled: { label: "Dappled light", phrase: "filtered, patterned light that moves across walls and floors" },
  "hard-sun": { label: "Hard sun", phrase: "strong sun and crisp shadow used as a graphic element" },
};

export const paletteCopy: Readonly<Record<PaletteTone, { label: string; swatch: string }>> = {
  "warm-earth": { label: "Warm earth", swatch: "#a8865f" },
  ivory: { label: "Ivory", swatch: "#e6dccb" },
  burgundy: { label: "Burgundy", swatch: "#6b1c24" },
  terracotta: { label: "Terracotta", swatch: "#bd6f4b" },
  celadon: { label: "Celadon", swatch: "#a5b49c" },
  "candle-gold": { label: "Candle gold", swatch: "#d6a24e" },
  walnut: { label: "Walnut", swatch: "#5a3a26" },
  "sea-blue": { label: "Sea blue", swatch: "#6f8ea3" },
};

export const compositionCopy: Readonly<Record<Composition, { label: string; phrase: string }>> = {
  environmental: { label: "Environmental", phrase: "wide frames that place people and objects within their world" },
  detail: { label: "Detail", phrase: "close studies of hands, texture, and material" },
  portrait: { label: "Portrait", phrase: "direct, composed portraiture with room to breathe" },
  "still-life": { label: "Still life", phrase: "arranged still life with deliberate spacing" },
  "layered-depth": { label: "Layered depth", phrase: "frames within frames, foreground and threshold creating depth" },
  "negative-space": { label: "Negative space", phrase: "generous negative space that lets a single subject rest" },
  movement: { label: "Movement", phrase: "fabric, bodies, and light caught mid-motion" },
  overhead: { label: "Overhead", phrase: "top-down arrangements with a graphic, editorial order" },
};

export const locationCopy: Readonly<Record<LocationType, string>> = {
  "villa-garden": "Villa & garden",
  "historic-courtyard": "Historic courtyard",
  "city-street": "City street",
  terrace: "Terrace",
  "traditional-interior": "Traditional interior",
  "dining-room": "Dining room",
  studio: "Studio",
};

export const categoryCopy: Readonly<Record<ProjectCategory, string>> = {
  Weddings: "Weddings",
  Fashion: "Fashion",
  Commercial: "Commercial",
  Editorial: "Editorial",
  Architecture: "Architecture",
  Product: "Product",
};

export const facetNames = ["category", "quality", "mood", "lighting", "palette", "composition", "location"] as const;
export type FacetName = (typeof facetNames)[number];

export interface FacetTerm {
  readonly facet: FacetName;
  readonly value: string;
}

const term = (facet: FacetName, value: string): FacetTerm => ({ facet, value });

/**
 * Everyday language → structured facets. Multi-word phrases are matched before single words.
 * Keep entries honest: a word should only map to facets a reasonable reader would agree with.
 */
export const lexicon: Readonly<Record<string, readonly FacetTerm[]>> = {
  // Categories
  wedding: [term("category", "Weddings")],
  weddings: [term("category", "Weddings")],
  bride: [term("category", "Weddings")],
  groom: [term("category", "Weddings")],
  elopement: [term("category", "Weddings"), term("quality", "intimate")],
  marriage: [term("category", "Weddings")],
  engagement: [term("category", "Weddings")],
  fashion: [term("category", "Fashion")],
  couture: [term("category", "Fashion")],
  lookbook: [term("category", "Fashion")],
  clothing: [term("category", "Fashion")],
  campaign: [term("category", "Commercial")],
  commercial: [term("category", "Commercial")],
  advertising: [term("category", "Commercial")],
  brand: [term("category", "Commercial")],
  hospitality: [term("category", "Commercial"), term("location", "dining-room")],
  restaurant: [term("category", "Commercial"), term("location", "dining-room")],
  hotel: [term("category", "Commercial")],
  food: [term("category", "Commercial"), term("location", "dining-room")],
  magazine: [term("category", "Editorial"), term("quality", "editorial")],
  portrait: [term("category", "Editorial"), term("composition", "portrait")],
  portraits: [term("category", "Editorial"), term("composition", "portrait")],
  portraiture: [term("category", "Editorial"), term("composition", "portrait")],
  architecture: [term("category", "Architecture"), term("quality", "architectural")],
  interior: [term("category", "Architecture")],
  interiors: [term("category", "Architecture")],
  building: [term("category", "Architecture")],
  product: [term("category", "Product")],
  products: [term("category", "Product")],
  "still life": [term("category", "Product"), term("composition", "still-life")],
  objects: [term("category", "Product")],
  ceramics: [term("category", "Product")],
  packshot: [term("category", "Product")],
  "e-commerce": [term("category", "Product")],
  ecommerce: [term("category", "Product")],

  // Visual qualities
  cinematic: [term("quality", "cinematic")],
  film: [term("quality", "cinematic")],
  filmic: [term("quality", "cinematic")],
  movie: [term("quality", "cinematic")],
  raw: [term("quality", "raw")],
  candid: [term("quality", "raw")],
  documentary: [term("quality", "raw")],
  imperfect: [term("quality", "raw")],
  gritty: [term("quality", "raw")],
  unposed: [term("quality", "raw")],
  intimate: [term("quality", "intimate")],
  personal: [term("quality", "intimate")],
  close: [term("quality", "intimate")],
  minimal: [term("quality", "minimal")],
  minimalist: [term("quality", "minimal")],
  clean: [term("quality", "minimal")],
  simple: [term("quality", "minimal")],
  restrained: [term("quality", "minimal")],
  refined: [term("quality", "minimal"), term("quality", "editorial")],
  expensive: [term("quality", "minimal"), term("quality", "editorial")],
  luxury: [term("quality", "minimal"), term("quality", "editorial")],
  luxurious: [term("quality", "minimal"), term("quality", "editorial")],
  premium: [term("quality", "minimal"), term("quality", "editorial")],
  dramatic: [term("quality", "dramatic")],
  drama: [term("quality", "dramatic")],
  bold: [term("quality", "dramatic")],
  moody: [term("quality", "dramatic"), term("quality", "cinematic")],
  dark: [term("quality", "dramatic"), term("lighting", "dusk")],
  contrast: [term("quality", "dramatic")],
  shadow: [term("quality", "dramatic"), term("lighting", "hard-sun")],
  shadows: [term("quality", "dramatic"), term("lighting", "hard-sun")],
  "strong shadows": [term("quality", "dramatic"), term("lighting", "hard-sun")],
  warm: [term("quality", "warm")],
  warmth: [term("quality", "warm")],
  sunlit: [term("quality", "warm"), term("lighting", "golden-hour")],
  monochrome: [term("quality", "monochrome")],
  "black and white": [term("quality", "monochrome")],
  "black-and-white": [term("quality", "monochrome")],
  "b&w": [term("quality", "monochrome")],
  grayscale: [term("quality", "monochrome")],
  greyscale: [term("quality", "monochrome")],
  architectural: [term("quality", "architectural")],
  graphic: [term("quality", "architectural")],
  geometric: [term("quality", "architectural")],
  geometry: [term("quality", "architectural")],
  editorial: [term("quality", "editorial")],
  nostalgic: [term("quality", "nostalgic")],
  nostalgia: [term("quality", "nostalgic")],
  vintage: [term("quality", "nostalgic")],
  retro: [term("quality", "nostalgic")],
  "old world": [term("quality", "nostalgic")],
  "old-world": [term("quality", "nostalgic")],
  weathered: [term("quality", "nostalgic")],
  experimental: [term("quality", "experimental")],
  abstract: [term("quality", "experimental")],
  surreal: [term("quality", "experimental")],
  "avant-garde": [term("quality", "experimental")],

  // Moods
  quiet: [term("mood", "quiet")],
  calm: [term("mood", "quiet"), term("mood", "serene")],
  still: [term("mood", "quiet")],
  stillness: [term("mood", "quiet")],
  soft: [term("mood", "quiet"), term("lighting", "open-shade")],
  hushed: [term("mood", "quiet")],
  tender: [term("mood", "tender")],
  gentle: [term("mood", "tender")],
  romantic: [term("mood", "romantic")],
  romance: [term("mood", "romantic")],
  love: [term("mood", "romantic")],
  contemplative: [term("mood", "contemplative")],
  reflective: [term("mood", "contemplative")],
  meditative: [term("mood", "contemplative")],
  thoughtful: [term("mood", "contemplative")],
  sensual: [term("mood", "sensual")],
  elegant: [term("mood", "timeless"), term("mood", "sensual")],
  convivial: [term("mood", "convivial")],
  joyful: [term("mood", "convivial")],
  celebration: [term("mood", "convivial")],
  gathering: [term("mood", "convivial")],
  timeless: [term("mood", "timeless")],
  classic: [term("mood", "timeless")],
  serene: [term("mood", "serene")],
  peaceful: [term("mood", "serene")],
  tranquil: [term("mood", "serene")],

  // Light
  "golden hour": [term("lighting", "golden-hour")],
  sunset: [term("lighting", "golden-hour")],
  sunlight: [term("lighting", "golden-hour")],
  golden: [term("lighting", "golden-hour"), term("quality", "warm")],
  dusk: [term("lighting", "dusk")],
  twilight: [term("lighting", "dusk")],
  evening: [term("lighting", "dusk")],
  "blue hour": [term("lighting", "dusk")],
  night: [term("lighting", "dusk"), term("lighting", "candlelight")],
  candle: [term("lighting", "candlelight")],
  candles: [term("lighting", "candlelight")],
  candlelight: [term("lighting", "candlelight")],
  candlelit: [term("lighting", "candlelight")],
  window: [term("lighting", "window-light")],
  "window light": [term("lighting", "window-light")],
  "natural light": [term("lighting", "window-light"), term("lighting", "open-shade")],
  daylight: [term("lighting", "window-light"), term("lighting", "open-shade")],
  shade: [term("lighting", "open-shade")],
  overcast: [term("lighting", "open-shade")],
  dappled: [term("lighting", "dappled")],
  filtered: [term("lighting", "dappled")],
  "hard light": [term("lighting", "hard-sun")],
  harsh: [term("lighting", "hard-sun")],

  // Palette
  earthy: [term("palette", "warm-earth")],
  earth: [term("palette", "warm-earth")],
  neutral: [term("palette", "warm-earth"), term("palette", "ivory")],
  neutrals: [term("palette", "warm-earth"), term("palette", "ivory")],
  beige: [term("palette", "warm-earth")],
  sand: [term("palette", "warm-earth")],
  stone: [term("palette", "warm-earth"), term("location", "historic-courtyard")],
  ivory: [term("palette", "ivory")],
  cream: [term("palette", "ivory")],
  white: [term("palette", "ivory")],
  linen: [term("palette", "ivory")],
  burgundy: [term("palette", "burgundy")],
  red: [term("palette", "burgundy")],
  wine: [term("palette", "burgundy")],
  crimson: [term("palette", "burgundy")],
  terracotta: [term("palette", "terracotta")],
  orange: [term("palette", "terracotta")],
  rust: [term("palette", "terracotta")],
  green: [term("palette", "celadon")],
  sage: [term("palette", "celadon")],
  celadon: [term("palette", "celadon")],
  gold: [term("palette", "candle-gold")],
  amber: [term("palette", "candle-gold")],
  wood: [term("palette", "walnut")],
  wooden: [term("palette", "walnut")],
  timber: [term("palette", "walnut")],
  walnut: [term("palette", "walnut")],
  brown: [term("palette", "walnut")],
  blue: [term("palette", "sea-blue")],
  sea: [term("palette", "sea-blue")],
  coastal: [term("palette", "sea-blue")],
  mediterranean: [term("palette", "sea-blue"), term("palette", "terracotta")],

  // Composition
  wide: [term("composition", "environmental")],
  environmental: [term("composition", "environmental")],
  scenic: [term("composition", "environmental")],
  detail: [term("composition", "detail")],
  details: [term("composition", "detail")],
  "close-up": [term("composition", "detail")],
  "close up": [term("composition", "detail")],
  texture: [term("composition", "detail")],
  textures: [term("composition", "detail")],
  tactile: [term("composition", "detail")],
  depth: [term("composition", "layered-depth")],
  layered: [term("composition", "layered-depth")],
  "negative space": [term("composition", "negative-space")],
  spacious: [term("composition", "negative-space")],
  airy: [term("composition", "negative-space")],
  movement: [term("composition", "movement")],
  motion: [term("composition", "movement")],
  dynamic: [term("composition", "movement")],
  flowing: [term("composition", "movement")],
  overhead: [term("composition", "overhead")],
  "top-down": [term("composition", "overhead")],
  "flat lay": [term("composition", "overhead")],

  // Places
  garden: [term("location", "villa-garden")],
  villa: [term("location", "villa-garden")],
  countryside: [term("location", "villa-garden")],
  estate: [term("location", "villa-garden")],
  courtyard: [term("location", "historic-courtyard")],
  historic: [term("location", "historic-courtyard"), term("quality", "nostalgic")],
  city: [term("location", "city-street")],
  urban: [term("location", "city-street")],
  street: [term("location", "city-street")],
  terrace: [term("location", "terrace")],
  rooftop: [term("location", "terrace")],
  rooftops: [term("location", "terrace")],
  balcony: [term("location", "terrace")],
  japanese: [term("location", "traditional-interior")],
  japan: [term("location", "traditional-interior")],
  traditional: [term("location", "traditional-interior")],
  dining: [term("location", "dining-room")],
  dinner: [term("location", "dining-room"), term("lighting", "candlelight")],
  supper: [term("location", "dining-room")],
  table: [term("location", "dining-room")],
  studio: [term("location", "studio")],
};

/** Words that never carry visual meaning on their own. */
export const stopWords: ReadonlySet<string> = new Set([
  "a", "an", "and", "any", "are", "as", "at", "be", "but", "by", "can", "do", "feel", "feeling", "feels", "find", "for",
  "from", "get", "give", "have", "help", "how", "i", "i'd", "i'm", "in", "into", "is", "it", "its", "kind", "like", "looking",
  "make", "me", "more", "my", "need", "of", "on", "or", "our", "photo", "photos", "photograph", "photographs", "photography",
  "please", "really", "see", "shoot", "show", "some", "something", "that", "the", "their", "them", "there", "these", "this",
  "to", "us", "very", "visual", "want", "we", "with", "work", "would", "you", "your", "images", "image", "pictures", "style",
  "direction", "define", "strong", "quite", "bit", "little", "lot", "lots", "every", "all",
]);

/** Words that flip the next matched term into something to avoid. */
export const negationWords: ReadonlySet<string> = new Set(["not", "no", "without", "avoid", "never", "nothing", "less", "except", "instead"]);

export const serviceCopy: Readonly<Record<StudioServiceId, { label: string; description: string }>> = {
  photography: {
    label: "Photography",
    description: "A focused commission: we plan, photograph, and edit a considered set of images.",
  },
  "creative-direction": {
    label: "Creative direction",
    description: "Concept, references, casting notes, and on-set direction so every frame shares one point of view.",
  },
  "visual-production": {
    label: "Full visual production",
    description: "End-to-end production: concept, locations, styling, crew, photography, and delivery across formats.",
  },
};
